using System.ComponentModel.DataAnnotations;

namespace TicketManager.Web.Models;

/// <summary>
/// Represents a message added to a ticket discussion timeline.
/// </summary>
public class TicketComment
{
    /// <summary>
    /// Unique identifier generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Identifier of the ticket to which this comment belongs.
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// Name displayed as the comment author.
    /// </summary>
    [Required(ErrorMessage = "O nome e obrigatorio.")]
    [Display(Name = "Nome")]
    public string AuthorName { get; set; } = string.Empty;

    /// <summary>
    /// Comment text shown in the ticket details timeline.
    /// </summary>
    [Required(ErrorMessage = "O comentario e obrigatorio.")]
    [StringLength(1000, MinimumLength = 10, ErrorMessage = "O comentario deve ter entre 10 e 1000 caracteres.")]
    [Display(Name = "Comentario")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// UTC date and time when the comment was created.
    /// </summary>
    [Display(Name = "Criado em")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Ticket associated with this comment.
    /// </summary>
    public Ticket? Ticket { get; set; }
}